- name: ðŸš€ Sync to Azure WebJob Folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /site/wwwroot/App_Data/jobs/triggered/login-worker/
          # Adding these two lines helps bypass the connection reset error
          port: 21
          protocol: ftp
